module: Filestack
author: Filestack
github_url: http://github.com/filestack/filestack-ios

theme: fullwidth
clean: true

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

swift_build_tool: spm